name: Build & Release Grassy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv \
                              libgtk-4-1 libadwaita-1-0 \
                              gir1.2-gtk-4.0 gir1.2-adw-1

      - name: Install PyInstaller
        run: pip3 install pyinstaller pygobject requests appdirs

      - name: Build binary
        run: |
          pyinstaller --onefile --name grassy src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: grassy-linux
          path: dist/grassy


  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install pyinstaller pygobject requests appdirs

      - name: Build binary
        run: |
          pyinstaller --onefile --name grassy src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: grassy-windows
          path: dist/grassy.exe


  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from Makefile
        id: version
        run: |
          VERSION=$(make version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: grassy-linux
          path: release/

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: grassy-windows
          path: release/

      - name: Rename binaries
        run: |
          mv release/grassy release/grassy-linux || true
          mv release/grassy.exe release/grassy-windows.exe || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Grassy v${{ env.VERSION }}
          draft: false
          prerelease: false
          make_latest: true
          files: |
            release/grassy-linux
            release/grassy-windows.exe
